#
# It is recommended that you use /configanvil to edit theses config.
# You can still manually edit here if you like to. but if you do, don't forget to /anvilconfigreload after you changes !
#

# All anvil cost will be capped to limit_repair_value if enabled.
#
# In other words:
# For any anvil cost greater than limit_repair_value, Cost will be set to limit_repair_value.
limit_repair_cost: false

# Max cost value the Anvil can get to.
#
# Valid values include 0 to 1000.
# Cost will be displayed as "Too Expensive":
# - If Cost is above 39
# - And replace_too_expensive is disabled (false)
limit_repair_value: 39

# Whether the anvil's cost limit should be removed entirely.
#
# The anvil will still visually display "Too Expensive" if "replace_too_expensive" is disabled
# However, the action will be completable if xp requirement is meet.
remove_repair_limit: false

# Whenever anvil cost is above 39 should display the true price and not "Too Expensive".
#
# However, when bypassing "Too Expensive", anvil price will be displayed as Green.
# If the action is not completable, the cost will still be displayed as "Too expensive".
# That mean you also need to change other settings like remove_repair_limit or limit_repair_cost.
#
# Require ProtocoLib.
replace_too_expensive: false

# XP Level amount added to the anvil when the item is repaired by another item of the same type
#
# Valid values include 0 to 1000
item_repair_cost: 2

# XP Level amount added to the anvil when the item is renamed
#
# Valid values include 0 to 1000
item_rename_cost: 1

# XP Level amount added to the anvil when the item is repaired by an "unit"
# For example: a Diamond on a Diamond Sword
# What's considered unit for what can be edited on the unit repair configuration.
#
# Valid values include 0 to 1000
unit_repair_cost: 1

# XP Level amount added to the anvil when a sacrifice enchantment
# conflict with one of the left item enchantment
#
# Valid values include 0 to 1000
sacrifice_illegal_enchant_cost: 1

# Allow using color code and hexadecimal color.
#
# Color code are prefixed by "&" and hexadecimal color by "#".
# Color code will not be applied if it colors nothing. "&&" can be used to write "&".
allow_color_code: false
allow_hexadecimal_color: false

# Toggle if color should only be applicable if the player a certain permission.
#
# permission are "ca.color.code" for use of color code and "ca.color.hex" for use of hexadecimal color.
permission_needed_for_color: true

# Xp cost if the player use color in the items name on rename.
#
# Valid values include 0 to 1000.
use_of_color_cost: 0

# Work penalty increase the price for every anvil use.
# This config allow you to choose the comportment of work penalty.
# Vanilla work penalty formula can be represented as 2 * previous_penalty + 1. with start value equal to 0
# See https://minecraft.wiki/w/Anvil_mechanics#Anvil_uses for more detail
#
# Valid work penalty type is:
# - default: work penalty added and increased
# - increase_only: work penalty increased but not added
# - add_only: work penalty added but not increased
# - disabled: work penalty disabled
work_penalty_type: default

# Default limit to apply to any enchants missing from enchant_limits
#
# Valid values include 1 to 1000
default_limit: 5

# Override limits for specific enchants
#
# Enchantments not listed here will use the value of default_limit
#
# Overrides provided default from aqua_affinity to depth_strider won't change effect with extra levels
#
# Valid range of 1 - 255 for each enchantment
enchant_limits:
  minecraft:aqua_affinity: 1
  minecraft:binding_curse: 1
  minecraft:channeling: 1
  minecraft:flame: 1
  minecraft:infinity: 1
  minecraft:mending: 1
  minecraft:multishot: 1
  minecraft:silk_touch: 1
  minecraft:vanishing_curse: 1
  minecraft:depth_strider: 3 # anything more than 3 is treated as 3 by the game
  minecraft:protection: 4
  minecraft:fire_protection: 4
  minecraft:blast_protection: 4
  minecraft:projectile_protection: 4
  minecraft:feather_falling: 4
  minecraft:thorns: 3
  minecraft:respiration: 3
  minecraft:sharpness: 5
  minecraft:smite: 5
  minecraft:bane_of_arthropods: 5
  minecraft:knockback: 2
  minecraft:fire_aspect: 2
  minecraft:looting: 3
  minecraft:sweeping: 3
  minecraft:sweeping_edge: 3
  minecraft:efficiency: 5
  minecraft:unbreaking: 3
  minecraft:fortune: 3
  minecraft:power: 5
  minecraft:punch: 2
  minecraft:luck_of_the_sea: 3
  minecraft:lure: 3
  minecraft:frost_walker: 2
  minecraft:impaling: 5
  minecraft:riptide: 3
  minecraft:loyalty: 3
  minecraft:piercing: 4
  minecraft:quick_charge: 3
  minecraft:soul_speed: 3
  minecraft:swift_sneak: 3

# Multipliers used to calculate the enchantment's value in repair/combining
#
# Values here are pulled from the fandom wiki:
# https://minecraft.fandom.com/wiki/Anvil_mechanics#Costs_for_combining_enchantments
#
# If an enchantment is missing values here, or is less than 0, it will default to 0
#
# Calculated as: [Enchantment lvl] * [multiplier]
#
# With default values protection 4 would have a value of 4 when
# coming from either a book (4 * 1) or an item (4 * 1)
enchant_values:
  minecraft:aqua_affinity:
    item: 4
    book: 2
  minecraft:bane_of_arthropods:
    item: 2
    book: 1
  minecraft:binding_curse:
    item: 8
    book: 4
  minecraft:blast_protection:
    item: 4
    book: 2
  minecraft:channeling:
    item: 8
    book: 4
  minecraft:depth_strider:
    item: 4
    book: 2
  minecraft:efficiency:
    item: 1
    book: 1
  minecraft:flame:
    item: 4
    book: 2
  minecraft:feather_falling:
    item: 2
    book: 1
  minecraft:fire_aspect:
    item: 4
    book: 2
  minecraft:fire_protection:
    item: 2
    book: 1
  minecraft:fortune:
    item: 4
    book: 2
  minecraft:frost_walker:
    item: 4
    book: 2
  minecraft:impaling:
    item: 4
    book: 2
  minecraft:infinity:
    item: 8
    book: 4
  minecraft:knockback:
    item: 2
    book: 1
  minecraft:looting:
    item: 4
    book: 2
  minecraft:loyalty:
    item: 1
    book: 1
  minecraft:luck_of_the_sea:
    item: 4
    book: 2
  minecraft:lure:
    item: 4
    book: 2
  minecraft:mending:
    item: 4
    book: 2
  minecraft:multishot:
    item: 4
    book: 2
  minecraft:piercing:
    item: 1
    book: 1
  minecraft:power:
    item: 1
    book: 1
  minecraft:projectile_protection:
    item: 2
    book: 1
  minecraft:protection:
    item: 1
    book: 1
  minecraft:punch:
    item: 4
    book: 2
  minecraft:quick_charge:
    item: 2
    book: 1
  minecraft:respiration:
    item: 4
    book: 2
  minecraft:riptide:
    item: 4
    book: 2
  minecraft:silk_touch:
    item: 8
    book: 4
  minecraft:sharpness:
    item: 1
    book: 1
  minecraft:smite:
    item: 2
    book: 1
  minecraft:soul_speed:
    item: 8
    book: 4
  minecraft:swift_sneak:
    item: 8
    book: 4
  minecraft:sweeping:
    item: 4
    book: 2
  minecraft:sweeping_edge:
    item: 4
    book: 2
  minecraft:thorns:
    item: 8
    book: 4
  minecraft:unbreaking:
    item: 2
    book: 1
  minecraft:vanishing_curse:
    item: 8
    book: 4

# Disable enchantment merging for level above the set value
# Enchantment merging is when, for example, 2 unbreaking II book combine to give sharpness III
# But Enchantment above this value can still be applied. following the previous example, we could still apply a unbreaking III book to a sword
# Even if disable-merge-over of unbreaking is set to 2
# -1 mean enchantment merge for this enchantment is not disabled. default to -1 if absent.
disable-merge-over:
  # Sharpness is set to -1. it equivalent to it not being set to anything (and work as vanilla)
  sharpness: -1
  # If uncommented. 2 unbreaking II book would not give an unbreaking III book. but unbreaking III book can still be applied
  #unbreaking: 2

# Whether to show debug logging
debug_log: false

# Whether to show verbose debug logging
debug_log_verbose: false

# In case something when wrong with CustomAnvil packet manager.
# If you see "missing class exception" or similar you may test this.
# If enabled and Protocolib absent or disabled "Replace to expensive" will not work.
# ProtocoLib may also be used if the server is in an "unsupported" version even if this option is disabled.
force_protocolib: false

configVersion: 1.6.2
