main: io.delilaheve.UnsafeEnchants
name: UnsafeEnchants
version: 1.0.3
description: Allow all enchants to be combined
api-version: 1.18
load: POSTWORLD
author: DelilahEve
permissions:
  ue.unsafe:
    default: true
    description: Allow player to combine allowed "unsafe" enchants
  ue.unsafe_all:
    default: false
    description: Allow player to combine every "unsafe" enchants